name: ${PROJECT_NAME}-dev
services:
  backend:
    build:
      target: dev

  frontend:
    build:
      target: dev

  phpmyadmin:
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}

volumes:
  mysql-data:
    name: "${PROJECT_NAME}-dev-db"
