name: ${PROJECT_NAME}-dev
services:
  backend:
    build:
      target: dev
    volumes:
      - ./back-end:/app
      - /app/node_modules
      - /app/.angular
      - /app/.vscode

  frontend:
    build:
      target: dev
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.angular
      - /app/.vscode

  phpmyadmin:
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}

volumes:
  mysql-data:
    name: "${PROJECT_NAME}-dev-db"
