name: ${PROJECT_NAME}-prod
services:
  backend:
    build:
      target: prod
    restart: unless-stopped
    
  frontend:
    build:
      target: prod
    restart: unless-stopped

  mysql:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped

volumes:
  mysql-data:
    name: "${PROJECT_NAME}-prod-db"
